# 配置菜单导航的名称、路径和图标icon.
menu:
  Index:
    url: /
    icon: fas fa-home
  Tags:
    url: /tags
    icon: fas fa-tags
  Categories:
    url: /categories
    icon: fas fa-bookmark
  Archives:
    url: /archives
    icon: fas fa-archive
  About:
    url: /about
    icon: fas fa-user-circle
  Contact:
    url: /contact
    icon: fas fa-comments
  Friends:
    url: /friends
    icon: fas fa-address-book
  # 二级菜单写法如下
  #Medias:
  #  icon: fas fa-list
  #  children:
  #    - name: Musics
  #      url: /musics
  #      icon: fas fa-music
  #    - name: Movies
  #      url: /movies
  #      icon: fas fa-film
  #    - name: Books
  #      url: /books
  #      icon: fas fa-book
  #    - name: Galleries
  #      url: /galleries
  #      icon: fas fa-image

# 站点运行开始时间.
time:
  enable: true
  year: 2022 # 年份
  month: 05 # 月份
  date: 20 # 日期
  hour: 00 # 小时
  minute: 00 # 分钟
  second: 00 # 秒

# 首页封面轮播图的相关配置.
cover:
  showPrevNext: true # 是否显示左右切换按钮. Whether to display the left and right toggle buttons.
  showIndicators: true # 是否显示指示器. # Whether to display the indicators
  autoLoop: true # 是否自动轮播. Whether it is automatically rotated.
  duration: 120 # 切换延迟时间. Switching delay time.
  intervalTime: 5000 # 自动切换下一张的间隔时间. Automatically switch the interval of the next one.
  useConfig: false # 是否使用配置文件, 在 _data/covers.json 下配置推荐文章, false则使用主题在文章中的配置 cover coverImg
  # useConfig 使用方式: 将主题 hexo-theme-matery/source/_data/covers.json 移动到 my-blog/source/_data/下修改配置即可
  video:
    enable: false
    src:
      - https://txmov2.a.yximgs.com/upic/2021/04/09/22/BMjAyMTA0MDkyMjMwMDhfMTg1ODk2MDg4N180NzUyOTMyMjA4Nl8xXzM=_b_B8e080d7ede19e6674d48a9f12545007b.mp4?pkey=AAVAfNhi5_f-HGkIPXrY5w6nyf4JibwOY-WwdHgSJ2aSoi-2WQLpiYDunLbRZQuESz875eMdsepRlVFtXg9nuQY58uRc-7AsF0kEMNR6QYBj56g9JFFMSGdsoKK2-SV27u8&tag=1-1617978682-xpcwebprofile-0-lcvipceuti-9e40072f87531f1a&clientCacheKey=3xbbtbrfxqpccp4_b.mp4
      - https://txmov2.a.yximgs.com/upic/2021/04/09/21/BMjAyMTA0MDkyMTQyNDRfMTg1ODk2MDg4N180NzUyNjAyMzA0N18xXzM=_b_B83b004b85aba8eca3ded270637616575.mp4
      - https://txmov2.a.yximgs.com/upic/2021/04/09/21/BMjAyMTA0MDkyMTU4MDNfMTg1ODk2MDg4N180NzUyNzE0MzkyNV8xXzM=_b_Bf94cee6bd181efeaca64049bd2e4e276.mp4

# 配置首页显示"梦想"的语句.
dream:
  enable: true
  showTitle: true
  title:
  text: 海到无边天作岸，山登绝顶我为峰。 —— 林则徐

# 是否在首页显示音乐.
music:
  enable: false
  title: #非吸底模式有效
    enable: false
    show: 听听音乐
  autoHide: false
  server: netease
  type: playlist #require song, playlist, album, search, artist
  id: 503838841 #require	song id / playlist id / album id / search keyword
  fixed: true # 开启吸底模式
  autoplay: false # 是否自动播放
  theme: "#42b983"
  loop: "all"
  order: "random" # 'list', 'random'
  preload: "auto"
  volume: 0.4
  listFolded: true
  hideLrc: true # 隐藏歌词

# 单独的音乐页面.
musics:
  enable: false
  title: #非吸底模式有效
    enable: true
    show: 听听音乐
  server: tencent #require music platform: netease, tencent, kugou, xiami, baidu
  type: playlist #require song, playlist, album, search, artist
  id: 1776127550 #require song id / playlist id / album id / search keyword
  fixed: false # 开启吸底模式
  autoplay: true # 是否自动播放
  theme: "#42b983"
  loop: "all" # 音频循环播放, 可选值: 'all', 'one', 'none'
  order: "random" # 音频循环顺序, 可选值: 'list', 'random'
  preload: "auto" # 预加载，可选值: 'none', 'metadata', 'auto'
  volume: 0.7 # 默认音量，请注意播放器会记忆用户设置，用户手动设置音量后默认音量即失效
  listFolded: false # 列表默认折叠
  listMaxHeight: "525px" #列表最大高度

# 是否在首页显示视频.
video:
  enable: false
  showTitle: true
  title: 精彩视频
  url: # url和iframeUrl其中一个必填
  iframeUrl: #在bilibili或者爱奇艺分享时选择iframe，然后填那个url来这里，sample: //player.bilibili.com/player.html?aid=669520137&bvid=BV1oa4y1L7mw&cid=234543483&page=1
  pic:
  thumbnails:
  height: # 如：400
  autoplay: false # 是否自动播放
  theme: "#42b983"
  loop: false # 是否循环播放
  preload: "auto" # 预加载，可选值: 'none', 'metadata', 'auto'
  volume: 0.7

# 是否显示推荐文章的标题
recommend:
  enable: true
  showTitle: true
  useConfig: false # 是否使用配置文件, 在 _data/recommends.json 下配置推荐文章, false则会走主题配置的 top 属性
  # useConfig 使用方式: 将主题 hexo-theme-matery/source/_data/recommends.json 移动到 my-blog/source/_data/下修改配置即可

# 配置网站favicon和网站LOGO
favicon: /favicon.png
logo: /logo.png

# 首页 banner 中的第二个按钮的配置，包括按钮的显示名称、font awesome图标和按钮的超链接.
indexbtn:
  enable: true
  name: mygithub
  icon: fab fa-github
  url: https://github.com/jjlstruggle

# 首页 banner 中的第二行个人信息配置，留空即不启用
socialLink:
  github: https://github.com/jjlstruggle
  email: 3240124918@qq.com
  qq: 3240124918
  rss: false # true、false

# 是否激活文章 TOC 功能，并配置TOC支持选中哪些标题类型，这是全局配置。
# 可以在某篇文章的 Front-matter 中再加上`toc: false`，使该篇文章关闭TOC目录功能
toc:
  enable: true
  heading: h2, h3, h4
  collapseDepth: 0 # 目录默认展开层级
  showToggleBtn: true # 是否显示切换TOC目录展开收缩的按钮

# 代码块相关
code:
  lang: true # 代码块是否显示名称
  copy: true # 代码块是否可复制
  shrink: true # 代码块是否可以收缩
  break: true # 代码是否折行

# 是否激活文章末尾的打赏功能，默认激活（你替换为的你自己的微信、支付宝二维码图片、或者使用网络图片也可以）.
reward:
  enable: false
  title: 你的赏识是我前进的动力
  wechat: /medias/reward/wechat.png
  alipay: /medias/reward/alipay.jpg

# 是否激活复制文章时追加博客和作者的版权信息.
copyright:
  enable: false
  minCharNumber: 120 # 至少复制多少个字符就追加版权信息.
  description: 本文章著作权归作者所有，任何形式的转载都请注明出处。

# 是否激活mathjax数学公式，这是全局配置，但文章仍然不会都开启mathjax渲染，
# 考虑到mathjax加载比较耗时，你还需要在需要渲染的文章的Front-matter中再加上`mathjax: true`才行.
mathjax:
  enable: false
  cdn: https://cdn.bootcss.com/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML

# 文章字数统计、阅读时长、总字数统计等
# 文章信息--若要开启文章字数统计，需要安装 hexo-wordcount 插件，安装命令: `npm i --save hexo-wordcount`
postInfo:
  date: true # 发布日期
  update: true # 更新日期
  wordCount: true # 文章字数统计
  totalCount: true # 站点总文章字数
  min2read: false # 文章阅读时长
  readCount: false # 文章阅读次数

# 是否激活点击页面的'爱心'效果，默认激活.
clicklove:
  enable: false

# 是否激活页面樱花效果, 只在桌面版网页启用特效
# 下面三种特效建议选择一种就够了，
sakura:
  enable: false

# 是否激活页面鼠标星星跟随效果, 只在桌面版网页启用特效
mouseStar:
  enable: false

  # 是否激活页面飘雪效果, 只在桌面版网页启用特效
snowdown:
  enable: true

# 在”关于”页面中配置个人信息，包括头像、职业和个人介绍.
profile:
  avatar: /medias/avatar.jpg
  career: CV Engineer
  introduction: a somebody who touch fish everyday.

# 在“关于”页面配置"我的项目"信息，如果你不需要这些信息则可以将其设置为不激活或者将其删除.
myProjects:
  enable: false
  data:
    hexo-theme-matery:
      icon: fas fa-file-alt
      iconBackground: "linear-gradient(to bottom right, #66BB6A 0%, #81C784 100%)"
      url: http://github.com/blinkfox/hexo-theme-matery
      desc: This is a Hexo blog theme with 'Material Design' and responsive design.
    Fenix:
      icon: fas fa-database
      iconBackground: "linear-gradient(to bottom right, #F06292 0%, #EF5350 100%)"
      url: https://github.com/blinkfox/fenix
      desc: 这是 Spring Data JPA 复杂或动态 SQL 查询的扩展库。
    typora-vue-theme:
      icon: fas fa-file-alt
      iconBackground: "linear-gradient(to bottom right, #29B6F6 0%, #1E88E5 100%)"
      url: https://github.com/blinkfox/typora-vue-theme
      desc: This is a typora theme inspired by Vue document style.

# 在“关于”页面配置"我的技能"信息，如果你不需要这些信息则可以将其设置为不激活或者将其删除.
mySkills:
  enable: true
  data:
    React:
      background: "linear-gradient(to right, #FF0066 0%, #FF00CC 100%)"
      percent: 2%
    Vue:
      background: "linear-gradient(to right, #9900FF 0%, #CC66FF 100%)"
      percent: 1%
    HTML5:
      background: "linear-gradient(to right, #2196F3 0%, #42A5F5 100%)"
      percent: 4%
    CSS:
      background: "linear-gradient(to right, #00BCD4 0%, #80DEEA 100%)"
      percent: 3%
    程序设计:
      background: "linear-gradient(to right, #FFEB3B 0%, #FFF176 100%)"
      percent: 0%

# 在“关于”页面配置"我的相册"图片，如果你不需要这些信息则可以将其设置为不激活或者将其删除.
myGallery:
  enable: false
  data:
    - /medias/featureimages/22.jpg

# Whether to display post-calender in the `archive` page
# 设置在归档页面中是否显示'文章日历'控件
postCalendar: true

tcaptcha:
  enable: false
  appid: xxxxxxxxxx # 你的appid

# Valine 评论模块的配置，默认为不激活，如要使用，就请激活该配置项，并设置 appId 和 appKey.
valine:
  enable: true
  appId: RTmqJoW0x9Ji7W5Q8Ygwotnq-gzGzoHsz
  appKey: w4uyFIqK38YPqYz6FzD1K0rR
  notify: false
  verify: false
  visitor: true
  avatar: "mm"
  pageSize: 10
  placeholder: "say everything you want" # Comment Box placeholder
  background: /medias/comment_bg.png
  coolpushkey:

# 配置是否在 header 中显示 fork me on github 的图标，默认为true，你可以修改为你的仓库地址.
githubLink:
  enable: true
  url: https://github.com/blinkfox/hexo-theme-matery
  title: Fork Me

# 阅读文章的密码验证功能，如要使用此功能请激活该配置项，并在对应文章的Front-matter中写上'password'的键和加密后的密文即可.
# 请注意：为了保证密码原文不会被泄露到网页中，文章的密码必须是通过'SHA256'加密的，这样就不会被破解.
verifyPassword:
  enable: false
  promptMessage: 请输入访问本文章的密码
  errorMessage: 密码错误，将返回主页！

busuanziStatistics:
  enable: false
  totalTraffic: false # 总访问量
  totalNumberOfvisitors: false # 总人次

# 添加 Google Analytics 配置
googleAnalytics:
  enable: false
  id:

# 添加 baidu Analytics 配置
baiduAnalytics:
  enable: true
  id: 5691fec70728c0712e4a790d6244d268

baiduPush: true

# 使用到的前端库，可按需替换成对应的CDN地址，如果下面未指定具体的版本号，使用最新的版本即可.
# 注：jsdelivr可以自动帮你生成.min版的js和css，所以你在设置js及css路径中可以直接写.min.xxx
libs:
  css:
    matery: /css/matery.css
    mycss: /css/my.css
    gallery: /css/gallery.css
    fontAwesome: /libs/awesome/css/all.min.css # V6 20220313
    materialize: /libs/materialize/materialize.min.css # 1.0.0 20211109
    aos: /libs/aos/aos.css
    animate: /libs/animate/animate.min.css # V3.5.1
    lightgallery: /libs/lightGallery/css/lightgallery.min.css # V1.10.0
    dplayer: /libs/dplayer/DPlayer.min.css
    jqcloud: /libs/jqcloud/jqcloud.css
    tocbot: /libs/tocbot/tocbot.css
    prism: /libs/prism/prism.css
    mermaid: /libs/mermaid/mermaid.min.css
    fancybox: /libs/fancybox/jquery.fancybox.css
    justifiedGallery: /libs/justifiedGallery/justifiedGallery.min.css
  js:
    matery: /js/matery.js
    jquery: /libs/jquery/jquery-3.6.0.min.js #3.6.0 20211109
    materialize: /libs/materialize/materialize.min.js # 1.0.0
    masonry: /libs/masonry/masonry.pkgd.min.js # v4.0.0
    aos: /libs/aos/aos.js
    scrollProgress: /libs/scrollprogress/scrollProgress.min.js
    lightgallery: /libs/lightGallery/js/lightgallery-all.min.js # V1.10.0
    clicklove: /libs/others/clicklove.js
    sakura: /libs/others/sakura-half.js
    star: /libs/others/star.js
    snow: /libs/others/snow.js
    tcaptcha: /libs/others/TencentCaptcha.js
    busuanzi: /libs/others/busuanzi.pure.mini.js
    dplayer: /libs/dplayer/DPlayer.min.js
    crypto: /libs/cryptojs/crypto-js.min.js
    echarts: /libs/echarts/echarts.min.js
    valine: /libs/valine/Valine.min.js # 若想保持最新版，请替换为 https://unpkg.com/valine/dist/Valine.min.js  默认为 /libs/valine/Valine.min.js
    jqcloud: /libs/jqcloud/jqcloud-1.0.4.min.js
    tocbot: /libs/tocbot/tocbot.min.js
    canvas_nest: /libs/background/canvas-nest.js
    ribbon: /libs/background/ribbon.min.js
    ribbonRefresh: /libs/background/ribbon-refresh.min.js
    ribbon_dynamic: /libs/background/ribbon-dynamic.js
    instantpage: /libs/instantpage/instantpage.js
    mermaid: /libs/mermaid/mermaid.min.js
    fancybox: /libs/fancybox/fancybox.js
    justifiedGallery: /libs/justifiedGallery/justifiedGallery.min.js
    codeblock: /libs/codeBlock/codeBlockFuction.js
    codelang: /libs/codeBlock/codeLang.js
    codecopy: /libs/codeBlock/codeCopy.js
    codeshrink: /libs/codeBlock/codeShrink.js
    typed: /libs/typed/typed.min.js

# 无文章特色图片时需要显示的文章特色图片.
featureImages:
  - /medias/featureimages/15.jpg
  - /medias/featureimages/16.jpg
  - /medias/featureimages/17.jpg
  - /medias/featureimages/18.jpg
  - /medias/featureimages/22.jpg
  - /medias/featureimages/23.jpg

reprint:
  enable: true # whether enable reprint section 是否启用“转载规则限定模块”
  default: cc_by

daovoice:
  enable: false
  app_id:

tidio:
  enable: false
  public_key:

# 腾讯兔小巢，见https://txc.qq.com/
tuxiaochao:
  enable: false
  productId:
#背景canvas-nest
canvas_nest:
  enable: false
  color: 0,0,255 # 线条颜色, 默认: '0,0,0' ；三个数字分别为(R,G,B)，注意用,分割
  pointColor: 0,0,255 # 交点颜色, 默认: '0,0,0' ；三个数字分别为(R,G,B)，注意用,分割
  opacity: 0.7 # 线条透明度（0~1）, 默认: 0.5
  zIndex: -1 # 背景的 z-index 属性，css 属性用于控制所在层的位置, 默认: -1.
  count: 49 # 线条的总数量, 默认: 99

# 背景静止彩带.
ribbon:
  enable: false
  size: 150 # 彩带大小, 默认: 90.
  alpha: 0.6 # 彩带透明度 (0 ~ 1), 默认: 0.6.
  zIndex: -1 # 背景的z-index属性，css属性用于控制所在层的位置, 默认: -1.
  clickChange: false # 设置是否每次点击都更换彩带.

# 背景动态彩带.
ribbon_dynamic:
  enable: true

# sharejs文章分享模块.
# 支持顺序，可选项目为twitter, facebook, google, qq, qzone, wechat, weibo, douban, linkedin.
sharejs:
  enable: true
  sites: twitter,facebook,google,qq,qzone,wechat,weibo,douban,linkedin

# addthis文章分享模块.
addthis:
  enable: false
  pubid: # 前往https://www.addthis.com/获取

subtitle:
  enable: true
  loop: true # 是否循环
  showCursor: true # 是否显示光标
  startDelay: 300 # 开始延迟
  typeSpeed: 150 # 打字速度
  backSpeed: 25 # 删除速度
  sub:
    - 在神话里刻下自己的名字，在传说中书写自己的篇章！
    - 我们终将重逢!

# 手机二级菜单.
navMenu:
  mleft: false # 二级侧栏子菜单是否对齐左边
  bgColor: " " # 二级侧栏子菜单背景颜色,留空即为全局背景色

# 网页预加载.
instantpage:
  enable: true

# banner 是否每日切换.
# 若为 false, 则 banner 默认为 /medias/banner/0.jpg
banner:
  enable: false

#ICP备案信息尾部显示
icp:
  enable: true
  url: https://www.beianx.cn/search/%e9%84%82ICP%e5%a4%872021017709%e5%8f%b7
  text: 鄂ICP备2021017709号-1

# CDN访问加速
# 第一次使用本功能，一定要先配置url，再`hexo cl && hexo g && hexo d`部署到GitHub的仓库，注意！必须是GitHub的仓库！
# 如果必须要使用国内的coding或者gitee，可以采用双部署，同时将网站部署到两个仓库（其中一个必须是GitHub的仓库）
# URL配置规则（例子如下）： https://cdn.jsdelivr.net/gh/你的GitHub用户名/你的仓库名
# 更多关于访问速度优化，请查看：https://blog.sky03.cn/posts/42790.html
# 注：jsdelivr可以自动帮你生成.min版的js和css，所以你在上面设置js及css路径中可以直接写.min.xxx
jsDelivr:
  url: # https://cdn.jsdelivr.net/gh/skyls03/skyls03.github.io

# 网站背景图
background:
  enable: false
  url: "https://cdn.jsdelivr.net/gh/Tokisaki-Galaxy/res/site/medias/background.jpg"

# 说说 https://artitalk.js.org/
artitalk:
  enable: false
  appId: # xxxxx
  appKey: # xxxxxx

# 哔哔功能配置
# 登陆leancloud创建应用。进入应用后，点击创建 Class，将「 Class 名称」命名为 content
# 点击刚刚创建的content Class，点击添加列并创建名称为content的列，类型为String，注意列注释也要填写（随意填）
# 记录appid，masterkey，api域名
# 输入:hexo new page bb
# hexo就在source文件夹下创建了bb/index.md。
# 修改index.md的frontmater下的layout为bb：
# ---
# title: 黑石说
# layout: bb
# ---
# 里面的文字可以自己随意加，会显示在哔哔的上方。
# 关注公众号 "黑石哔哔"，发送: //bindCurrentUser:你的APPID,你的MASTERKEY,你的RESTAPI
# 可用leancloud国际版，国际版api为 https://appid前八位.api.lncldglobal.com
bbtime:
  enable: false
  appId: # 你的appId
  appKey: # 你的appKey
  serverURLs: # https://你的api

# 图表绘制插件
# 建议更换更换hexo-renderer-markdown-it引擎。参考下面链接
# https://github.com/hexojs/hexo-renderer-markdown-it
# https://github.com/hexojs/hexo-renderer-markdown-it/wiki/Advanced-Configuration
# 安装配置方法
# yarn remove hexo-renderer-marked
# yarn add hexo-renderer-markdown-it hexo-tag-mermaid
# 注意：hexo-renderer-markdown-it 比默认引擎更快，可选择插件较多，请认真看上面两个链接教程。
# mermaid语法教程 https://mermaid-js.github.io/mermaid/#/
# 使用方法：
# 在post文章中填写mermaid语句，需要使用{% mermaid %} 包裹
# {% mermaid %}
# [mermaid 语句正文]
# {% endmermaid %}
# 样例如下所示：
# {% mermaid %}
# graph TD
#     A[Christmas] -->|Get money| B(Go shopping)
#     B --> C{Let me think}
#     C -->|One| D[Laptop]
#     C -->|Two| E[iPhone]
#     C -->|Three| F[Car]
# {% endmermaid %}
# mermaid chart。 依赖hexo-tag-mermaid
mermaid: ## mermaid url https://github.com/knsv/mermaid
  enable: false # default false
  version: "latest" # default v7.1.2
  options:
  # find more api options from https://github.com/knsv/mermaid/blob/master/src/mermaidAPI.js
  #startOnload: true  // default true

preloader:
  enable: true
