name: Build and Deploy to aliyun

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: Install npm dependencies
        run: npm i
      - name: Run build task
        run: yarn build
      - name: ssh deploy
        uses: easingthemes/ssh-deploy@v2.2.11
        env:
          CI: true
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: blog # 这是要复制到阿里云静态服务器的文件夹名称
          REMOTE_HOST: "121.40.19.111" # 你的阿里云公网地址
          REMOTE_USER: root # 阿里云登录后默认为 root 用户，并且所在文件夹为 root
          TARGET: /usr/share/nginx/html # 打包后的文件夹
